// <auto-generated />
namespace DoAnCoThanh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class upd_database : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upd_database));
        
        string IMigrationMetadata.Id
        {
            get { return "202201041422461_upd_database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
